name: Django CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecutar cuando se haga push a la rama principal
  pull_request:
    branches:
      - main  # Ejecutar para PRs hacia la rama principal

jobs:
  build:
    runs-on: ubuntu-latest  # El entorno de ejecución (Ubuntu)

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Acción para obtener el código del repositorio

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Puedes usar la versión de Python que prefieras

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instalar dependencias desde el archivo requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate  # Ejecutar migraciones de la base de datos

      - name: Run tests
        run: |
          python manage.py test  # Ejecutar las pruebas de Django

      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa <EC2_IP> >> ~/.ssh/known_hosts
        env:
          EC2_IP: ${{ secrets.EC2_IP }}  # Agrega la IP de tu EC2 en los secretos de GitHub

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            cd /path/to/your/project
            git pull origin main  # Actualizar el código desde GitHub
            source /path/to/your/venv/bin/activate  # Activar el entorno virtual
            pip install -r requirements.txt  # Instalar dependencias
            python manage.py migrate  # Ejecutar migraciones de la base de datos
            python manage.py collectstatic --noinput  # Recoger archivos estáticos
            sudo systemctl restart gunicorn  # Reiniciar el servicio Gunicorn
            sudo systemctl restart nginx  # Reiniciar Nginx (si lo usas)
          EOF
        env:
          EC2_IP: ${{ secrets.EC2_IP }}  # Agrega la IP de tu EC2 en los secretos de GitHub
